# version 0.4
services:
  postgres:
    image: postgres
    container_name: katpool-db
    networks:
      - backend
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    restart: always

  katpool-app:
    image: ghcr.io/argonmining/katpool-app:v2408.1b-main
    pull_policy: always
    container_name: katpool-app
    depends_on:
      - postgres
      - katpool-monitor
      - pushgateway
    ports:
      - "7777:7777"
    networks:
      - backend
    volumes:
      - ./config:/app/config
      - ./wasm:/app/wasm
    env_file:
      - .env
    restart: always

  katpool-monitor:
    image: ghcr.io/argonmining/katpool-monitor:v2408.1b-main
    pull_policy: always
    container_name: katpool-monitor
    depends_on:
      - postgres
    networks:
      - backend
    env_file:
      - .env
    ports:
      - "9301:9301"
      - "9300:9300"
    restart: always

  katpool-payment:
    image: ghcr.io/argonmining/katpool-payment:v2408.1b-main
    pull_policy: always
    container_name: katpool-payment
    depends_on:
      - postgres
    volumes:
      - ./config:/app/config
      - ./wasm:/app/wasm
    networks:
      - backend
    env_file:
      - .env
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: katpool-prmths
    depends_on:
      - postgres
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    networks:
      - backend
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always

  pushgateway:
    image: prom/pushgateway
    container_name: katpool-pushgateway
    networks:
      - backend
    restart: always

  nginx:
    container_name: katpool-nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    #      - ./htpasswd:/etc/nginx/.htpasswd
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - prometheus
      - katpool-monitor
    restart: always
  # postgres-backup:
  #   image: katpool-backup:0.4
  #   container_name: katpool-backup
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./backup/files:/backup/files
  #   networks:
  #     - backend
  #   restart: always

networks:
  backend:
    driver: bridge
    name: katpool-app_backend
