version: '0.1'
services:
  postgres:
    image: postgres
    container_name: kaspool-db
#    ports:
#      - "5432:5432"
    networks:
      - backend    
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    restart: always      
      
  kaspool-app:
    image: kaspool-app:0.1
    container_name: kaspool-app
    depends_on:
      - postgres
    ports:
      - "7777:7777"
      - "9100:9100"
    networks:
      - backend        
    env_file:
      - .env
    restart: always      

  kaspool-monitor:
    image: kaspool-monitor:0.1
    container_name: kaspool-monitor
    depends_on:
      - postgres
    ports:
#      - "9300:9300"
      - "9301:9301"
    networks:
      - backend       
    env_file:
      - .env
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: kaspool-prmths
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - backend       
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
    
networks:
  backend:
