# version 0.3
services:
  postgres:
    image: postgres
    container_name: kaspool-db
    networks:
      - backend    
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    restart: always

  kaspool-app:
    image: kaspool-app:0.33aragon
    container_name: kaspool-app
    depends_on:
      - postgres
    ports:
      - "7777:7777"
      - "9100:9100"
    networks:
      - backend        
    env_file:
      - .env
    restart: always

  kaspool-monitor:
    image: kaspool-monitor:0.1
    container_name: kaspool-monitor
    depends_on:
      - postgres
    ports:
      - "9301:9301"
    networks:
      - backend       
    env_file:
      - .env
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: kaspool-prmths
    depends_on:
      - kaspool-app    
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - backend       
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always

  pushgateway:
    image: prom/pushgateway
    container_name: kaspool-pushgateway
    depends_on:
      - kaspool-app     
    ports:
      - "9092:9091"
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge
