services:
  kaspad:
    container_name: kaspad
    image: supertypo/rusty-kaspad:v1.0.1 # Update this version for Rusty-Kaspa node upgrade
    restart: unless-stopped
    ports:
      - '16111:16111/tcp'
      - '16110:16110/tcp' # gRPC
      - '17110:17110/tcp' # wRPC (borsh)
      - '18110:18110/tcp' # wRPC (json)
    volumes:
      - /root/docker_deployment/kaspad_mainnet:/app/data/
    networks:
      - backend
    command: kaspad --yes --nologfiles --disable-upnp --utxoindex --rpclisten=0.0.0.0:16110 --rpclisten-borsh=0.0.0.0:17110 --rpclisten-json=0.0.0.0:18110
    logging:
      driver: journald
      options:
        tag: '{{.Name}}'

  # kaspad-test10: # REGULAR TESTNET
  #   container_name: kaspad-test10
  #   image: supertypo/rusty-kaspad:v1.0.1 # Update this version for Rusty-Kaspa node upgrade
  #   restart: unless-stopped
  #   ports:
  #     - '16211:16211/tcp'
  #     - '16210:16210/tcp' # gRPC
  #     - '17210:17210/tcp' # wRPC (borsh)
  #     - '18210:18210/tcp' # wRPC (json)
  #   volumes:
  #     - /root/docker_deployment/kaspad_testnet10:/app/data/
  #   networks:
  #     - backend
  #   command: kaspad --yes --nologfiles --disable-upnp --utxoindex --testnet --rpclisten=0.0.0.0:16210 --rpclisten-borsh=0.0.0.0:17210 --rpclisten-json=0.0.0.0:18210
  #   logging:
  #     driver: journald
  #     options:
  #       tag: '{{.Name}}'

networks:
  backend:
    driver: bridge
    name: katpool-app_backend
    external: true
