
kaspad_address: localhost:16110

# block_wait_time: time to wait since last new block message from kaspad before
# manually requesting a new block.  Examples are '500ms', '3s', '1m', etc.
block_wait_time: 3s

redis_address : localhost:6379

redis_channel : NewBlockTemplateChannel